### ISSUE TITLE
Auto create user for Google business accounts

### ISSUE THREAD

**Issue by georgringer** [georgringer/google_signin#3]
Idea: If a user tries to log in from a google business account, a new user should be created automatically.

A user template ensures a lot of options like creating an admin or creating users.

Further features:
- Enable for FE
- Enable for BE

**Comment by codemonkey1988** [comment]
I currently have a working version for backend authentication. A new backend user is created based on a given skeleton user when a new google user logs in that belongs to a configured organisation. Will do the frontend authentication on Sunday.
